<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- Metadata -->
    <AssemblyTitle>Demo Api Scalar Galaxy C#</AssemblyTitle>
    <AssemblyName>DemoApiScalarGalaxy</AssemblyName>
    <VersionPrefix>0.1.0</VersionPrefix> <!-- x-release-please-version -->
    <Description>The Scalar Galaxy is an example OpenAPI document to test OpenAPI tools and libraries. It&apos;s a fictional universe with fictional planets and fictional data. Get all the data for all planets.</Description>
    <OutputType>Library</OutputType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="DemoApiScalarGalaxy.Tests" />
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    <PackageReference Include="System.Text.Json" Version="9.0.9" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="System.Collections.Immutable" Version="8.0.0" />
  </ItemGroup>
</Project>
